### ISSUE TITLE
Psebay: Gravity Moto Trials

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#138] opened 2022-04-16 21:08 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Psebay: Gravity Moto Trials
- Game version: 4.0.45

# YoYo Loader summary
- Version: v. 4a9abe2

# Issues

- The game starts perfectly. 59fps
- Settings menu and store are responsive without issue
- No graphic glitches.
- BUT, when trying to choose a level, the touch screen does not respond! (although the music keeps playing and the dynamic background doesn't freeze) Weird!

# Screenshots
![image](https://user-images.githubusercontent.com/70182567/163691358-25792a0e-3469-4fa3-95ac-c75e89539242.png)
![image](https://user-images.githubusercontent.com/70182567/163691361-9f7be835-aa20-4ba6-8500-2de7ba33ddaa.png)

# Recommended labels

- A? Ingame (low)
- B?
- C?

**Comment by Rinnegatamante** [comment] 2022-04-16 22:32
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/29

**Closed by Rinnegatamante** 2022-04-16 22:32 UTC
