### ISSUE TITLE
Undergrave

### ISSUE THREAD

**Issue by CatoTheYounger97** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#67] opened 2022-04-11 18:18 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Undergrave https://wired-dreams-studio.itch.io/undergrave
- Game version: 1.0

# YoYo Loader summary
- Version: v0.1(8c9406)

# Issues

# Screenshots
![](https://?)
![2022-04-11-191413](https://user-images.githubusercontent.com/82458228/162803496-481f2479-dfc8-4ead-8f04-aecc124b7fb6.png)

![2022-04-11-191038](https://user-images.githubusercontent.com/82458228/162803416-be0111f0-cf68-4276-8ee3-7e818b3a9d8e.png)

# Recommended labels
-playable,
-full gamepad and touch support. in normal and forced windowed mode. 
-better performance in forced windowed mode, both modes 30fps+
-probably the best game I've  tested so far.

**Comment by Rinnegatamante** [comment] 2022-04-11 18:33
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/46

**Closed by Rinnegatamante** 2022-04-11 18:33 UTC
Labels: Playable
