### ISSUE TITLE
Surviving Titan

### ISSUE THREAD

**Issue by HiR3x** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#51] opened 2022-04-10 19:59 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Surviving Titans
- Game version: 1.0.12

# YoYo Loader summary
- Version: 0.1 (4257fd)

# Issues

The game boots and you can get in-game but the backgraund sprites are broken , music works olso the touch controll
# Screenshots
![](https://?)

# Recommended labels

- InGame(low)
- B?
- C?

**Comment by Rinnegatamante** [comment] 2022-04-10 19:59
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/50

**Closed by Rinnegatamante** 2022-04-10 19:59 UTC
