### ISSUE TITLE
Stolen Memory

### ISSUE THREAD

**Issue by CatoTheYounger97** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#69] opened 2022-04-11 18:23 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Stolen Memory https://liwalt.itch.io/stolen-memory
- Game version: 1.0

# YoYo Loader summary
- Version: v0.1(8c9406)

# Issues

# Screenshots
![](https://?)
![2022-04-11-190716](https://user-images.githubusercontent.com/82458228/162804578-51255137-5443-45c5-8486-df15d96e70d9.png)
![2022-04-11-190759](https://user-images.githubusercontent.com/82458228/162804651-7ecfcced-f848-4e19-bfb4-c6c6ba5f3e40.png)

# Recommended labels
-playable, touch controls only

**Comment by Rinnegatamante** [comment] 2022-04-11 18:37
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/53

**Closed by Rinnegatamante** 2022-04-11 18:37 UTC
Labels: Playable
