### ISSUE TITLE
Roll Catcher [waifu_grab]

### ISSUE THREAD

**Issue by panpeus** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#958] opened 2022-08-03 15:07 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: [Roll Catcher](https://crabowitz.itch.io/rollcatcher)
- Game version: ?

# YoYo Loader summary
- Version: f6d1dc

# Issues

# Screenshots
![](https://?)
![2022-07-19-213613-118830](https://user-images.githubusercontent.com/103394740/182642578-97c151af-e418-4a06-9783-b4e106754fe6.jpg)
![2022-07-19-212919-406369](https://user-images.githubusercontent.com/103394740/182642588-80d4d583-e7dc-4c2a-962b-0a1ab2f37630.jpg)
![2022-07-19-212850-060350](https://user-images.githubusercontent.com/103394740/182642590-ec69f151-9ef6-4808-bfcb-1fb8eea8a46f.jpg)

# Recommended labels

- Playable
- 59fps
- TOUCH (for portrait mode)
- keys.ini (when playing in landscape mode)

LANALOG=ON

UP=W
LEFT=A
DOWN=S
RIGHT=D
SQUARE=S
CROSS=
[yyl.log](https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/files/9252705/yyl.log)

**Comment by Rinnegatamante** [comment] 2022-08-03 15:38
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/843

**Closed by Rinnegatamante** 2022-08-03 15:38 UTC
Labels: Playable
