### ISSUE TITLE
Paper Knight

### ISSUE THREAD

**Issue by HiR3x** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#44] opened 2022-04-10 18:43 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Paper knight
- Game version: 1.0.87

# YoYo Loader summary
- Version: 0.1

# Issues

Paper knight works great only it has some bugs with the sprites of the knight

# Screenshots
![](https://?)

# Recommended labels

- Playable 
- B?
- C?

**Comment by Rinnegatamante** [comment] 2022-04-10 18:56
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/32

**Closed by Rinnegatamante** 2022-04-10 18:56 UTC
