### ISSUE TITLE
Gift Shop Factory [funfactory]

### ISSUE THREAD

**Issue by BrickCrypt** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#785] opened 2022-07-16 00:28 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: [Gift Shop Factory](https://manoelpdb.itch.io/giftshopfactory)
- Game version: 1.0.0
- Asset Swap: [Drink'n'Drive - Retro Racing](https://turboware.itch.io/drinkndrive)

# YoYo Loader summary
- Version: e52372

# Issues

# Screenshots
![2022-07-13-005557](https://user-images.githubusercontent.com/104641878/178661026-d3ffa542-264a-4485-b64f-e259f6f3064f.jpg)
![2022-07-13-005548](https://user-images.githubusercontent.com/104641878/178661032-e31da630-13ef-422a-9261-6ae51a7b4975.jpg)
![2022-07-13-005407](https://user-images.githubusercontent.com/104641878/178661037-ce69fc3e-5792-4ffe-bfcf-151facc4db73.jpg)

# Recommended labels

- Playable
- 60 fps
- Requires keys.ini

**CROSS=Z
START=CODE32
SQUARE=CODE32
CIRCLE=ESC
L1=ESC
R1=Z
UP=UP
DOWN=DOWN
LEFT=LEFT
RIGHT=RIGHT
LANALOG=ON**

**Comment by Rinnegatamante** [comment] 2022-07-16 09:50
Duplicate of https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/570

**Closed by Rinnegatamante** 2022-07-16 09:50 UTC
Labels: Playable
