### ISSUE TITLE
Celestial Raid [Celestial Raid Android]

### ISSUE THREAD

**Issue by BrickCrypt** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#784] opened 2022-07-16 00:28 UTC
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: [Celestial Raid](https://ebwc-games.itch.io/celestial-raid)
- Game version: 1.0.0

# YoYo Loader summary
- Version: e52372

# Recommendations

- I also recommend changing the screen size to 960*540 for a better experience
![image](https://user-images.githubusercontent.com/104641878/178657478-5d2f764d-bf1e-4391-91b9-3e40a5ccd043.png)

# Screenshots
![2022-07-13-002134](https://user-images.githubusercontent.com/104641878/178657524-330bfdf0-9506-42f6-a06a-cafabdb850a0.jpg)
![2022-07-13-002329](https://user-images.githubusercontent.com/104641878/178657551-11827979-6e07-4747-a501-ed6f82bbbdd1.jpg)
![2022-07-13-002453](https://user-images.githubusercontent.com/104641878/178657532-9456874b-1293-4c77-b2cb-db4681440b0f.jpg)

# Recommended labels

- Playable
- 59 fps
- Touch Controls & keys.ini

**UP=UP
DOWN=DOWN
LEFT=LEFT
RIGHT=RIGHT
LANALOG=ON**

**Comment by SofyUchiha** [comment] 2022-07-23 08:43
Duplicate of #226 ?

**Closed** 2022-07-23 09:02 UTC
Labels: Playable
